config/routes.rb
NomDePlume::Application.routes.draw do

  root :to => 'stories#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/:id', to: 'sessions#destroy'

  resources :users,   :except => [:index, :edit]

  resources :stories, :except => [:edit, :destroy, :new, :update]

  post '/receive' => 'message#receive'

  root :to => 'stories#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :phone_number, :password, :password_confirmation, :email
  has_many :lines
  has_many :stories, :through => :lines

  validates_presence_of :name, :password, :email, :phone_number
  validates_uniqueness_of :email, :phone_number
  validates :phone_number, :format => { :with => /\+\d{11}/, :on => :create, :message => "is invalid. Please include the area code" }
  validates :email,        :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :on => :create}
  
  before_validation(:on => :create) do
    num = phone_number.gsub(/\D/, '')
    num.prepend("1") unless num.length == 11
    self.phone_number = num.prepend("+")
  end



  #http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password
  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @stories = @user.stories.uniq

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        Twilio::SMS.create :to => @user.phone_number, :from => ENV["TWILIO_NUMBER"],
                         :body => "Thanks for signing up. On your turn, text to continue story,'PASS' to skip turn, or 'THE END' to end story."
        session[:user_id] = @user.id
        format.html { redirect_to '/stories', notice: 'User was successfully created.' }
        # format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id]) 
    @story = Story.last 
    if @story.next_user_id == @user.id
      next_user = (User.all - [@user] - [User.first]).sample
      @story.next_user_id = next_user.id
      @story.save
      WriteToSite.push_message(nil,nil,User.find(@story.next_user_id).name)
      Twilio::SMS.create :to => next_user.phone_number, :from => ENV["TWILIO_NUMBER"],
                     :body => @story.lines.last.content
    end
    @user.destroy if @user == current_user
    redirect_to logout_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="sign-up-container">
  <div class="sign-up-form">
    <h1>New user</h1>
    <hr>
    <%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>Some errors prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
               <% unless msg.include? "digest" %>
              <li><%= msg %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, "Nom de Plume", :class => "col-lg-3 control-label" %>
        <div class="col-lg-6">
          <%= f.text_field :name, :class => "form-control", :required => true %>
        </div>   
      </div>

      <div class="form-group">
        <%= f.label :email, :class => "col-lg-3 control-label" %>
        <div class="col-lg-6">
          <%= f.text_field :email, :class => "form-control", :required => true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone_number, :class => "col-lg-3 control-label" %>
        <div class="col-lg-6">
          <%= f.telephone_field :phone_number, :class => "form-control", :required => true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, :class => "col-lg-3 control-label" %>
        <div class="col-lg-6">
          <%= f.password_field :password, :class => "form-control", :required => true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, :class => "col-lg-3 control-label" %>
        <div class="col-lg-6">
          <%= f.password_field :password_confirmation, :class => "form-control", :required => true %>
          <br>
          <%= f.submit "Sign up", :class => "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6 user_show">

      <h2><%= @user.name %>'s stories</h2>

      <% @stories.each do |story| %>
        <li><%= link_to "#{story.lines.first.content}...", story %><span class="glyphicon glyphicon-chevron-right"></span></li>
      <% end %>
      <br>
      <% if current_user.id == params[:id].to_i %>
        <%= link_to "DELETE MY ACCOUNT", user_path(current_user), :class => "btn btn-danger", :method => "DELETE" %>
      <% end %>
    </div>

  </div>
</div>