config/routes.rb
NomDePlume::Application.routes.draw do

  root :to => 'stories#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/:id', to: 'sessions#destroy'

  resources :users,   :except => [:index, :edit]

  resources :stories, :except => [:edit, :destroy, :new, :update]

  post '/receive' => 'message#receive'

  root :to => 'stories#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :next_user_id
  has_many :lines
  has_many :users, :through => :lines

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    # featured
    @story = Story.last

    # gallery
    # next 9 stories go in gallery
    @stories = Story.order("created_at DESC").limit(10).drop(1)
    @author_photos = Dir.entries("app/assets/images/authors")
                      .delete_if{|f| f[0] == "."}.shuffle
    @deleted_user = User.new(name: '[DELETED USER]')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
    @deleted_user = User.new(name: '[DELETED USER]')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%#= render 'form' %>

<div id="story">
  <% Story.last.lines.each do |line| %>
    <span><%= line.content %></span>    
  <% end %>
</div>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<div class="featured-story">
  <div class="story-inner">
    <% @story.lines.each do |line| %>
      <span class='line' data-toggle='tooltip' title='Written by <%= (line.user || @deleted_user).name %>'><%= line.content %></span>
    <% end %>
  </div>
  <div class="featured-story-meta">
    <p>Waiting on ... <span id="next_user"><%=User.find(@story.next_user_id || 1).name %></span></p>
    <p>story started <%= time_ago_in_words(@story.created_at) %> ago</p>
  </div>
</div>



<div class="gallery col-lg-12" id="gallery">
  <div class="inner-gallery">
    <h2>Gallery</h2>
      <% @stories.each_with_index do |story, index| %>
        <div class="gallery-story col-lg-3">
          <%= image_tag "authors/#{@author_photos[index]}", :class => "author-profile" %>

          <div class="gallery-inner-text">
            <p><%= story.lines.first.content %></p>
            <p class="date-meta"><%= time_ago_in_words(story.created_at) %> ago</p>
            <p><%= link_to "read more", story %><span class="glyphicon glyphicon-chevron-right"></span></p>
          </div>
          
        </div>
      <% end %>
  </div>

</div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<div class="story-show">

  <div class="show-text">
    <% @story.lines.each do |line| %>
      <span class='line' data-toggle='tooltip' title='Written by <%= (line.user || @deleted_user).name %>'><%= line.content %></span>
    <% end %>
  	<p>story started <%= time_ago_in_words @story.created_at %> ago</p>
  </div>
</div>