config/routes.rb
NomDePlume::Application.routes.draw do

  root :to => 'stories#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/:id', to: 'sessions#destroy'

  resources :users,   :except => [:index, :edit]

  resources :stories, :except => [:edit, :destroy, :new, :update]

  post '/receive' => 'message#receive'

  root :to => 'stories#index'

end

app/views/layouts/_nav.html.erb
<div class="navbar">
  <div class="container">

    <!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <!-- Be sure to leave the brand out there if you want it shown -->
    <!-- Place everything within .navbar-collapse to hide it until above 768px -->
    <div class="nav-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", :root %></li>
        <%if params[:action] == "index"%>
          <li><%= link_to "Gallery", "/#gallery", :class => "scroll" %></li>
        <%end%>
        <li><a href="http://github.com/picodegallo/nom-de-plume">Fork us on GitHub</a></li>
        <li class="phone_number"><p class="navbar-text">text in at (646) 863-5311</p></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path %></li>
          <li>
            <%= link_to current_user.name, current_user %>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</div><!-- /.navbar -->

app/views/layouts/_text_in.html.erb
<div class="row">
  <div class="col-12">
    <div class="jumbotron">
      <h2>Text in at (646) 863-5311</h2>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "http://192.241.168.144:9292/faye.js"  %>
  <%= javascript_include_tag "application"  %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render "layouts/nav" %>


  <%#= render "layouts/text_in" %>

  <div class="logo-container">
    <!-- <embed class="logo" src="/assets/nomdeplume_pink.svg" type="image/svg+xml" /> -->
    <%= image_tag "nom_logo_250_300.png", :class => "logo" %>
  </div>

  <%= yield %>



</body>
</html>